=== LinggarM/platform-based-development-practicum/Pasca-UTS/Pertemuan 1/Praktikum 1 - Pasca UTS_wahyu/daftar-buku.dtd
<?xml version="1.0" encoding="UTF-8"?>
	<!ELEMENT daftar-buku (buku+)>
	<!ELEMENT buku (judul, pengarang)>
	<!ELEMENT judul (#PCDATA)>
	<!ELEMENT pengarang (#PCDATA)>

=== LinggarM/platform-based-development-practicum/Pasca-UTS/Pertemuan 1/prakXML/daftar-buku-eksternal.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE daftar-buku SYSTEM "daftar-buku.dtd">
<daftar-buku>
	<buku>
		<judul>XML untuk Pemula</judul>
		<pengarang>Ozalif Routing</pengarang>
	</buku>
	<buku>
		<judul>Belajar XML dalam Sekejap Mata</judul>
		<pengarang>Stefanus Sendana</pengarang>
	</buku>
	<buku>
		<judul>Mahir XML dan XSLT dalam 60 menit</judul>
		<pengarang>Eko Widiyanto</pengarang>
	</buku>
</daftar-buku>
